#!/bin/bash


# Set decoration geometry
berryc border_width       0
berryc inner_border_width 0
berryc title_height       30
berryc top_gap            0

# Set decoration colors
berryc focus_color         373737
berryc unfocus_color       141414
berryc inner_focus_color   373737 
berryc inner_unfocus_color 141414
berryc text_focus_color    ffffff
berryc text_unfocus_color  ffffff

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "ProFontWindowsCzech-9"
